### ISSUE TITLE
Example VCF content

### ISSUE THREAD

**Issue by serge2016** [m4merg/EphaGen#1]
Hello!

Here we can see `BRCA` instead of chromosome name:
https://github.com/m4merg/EphaGen/blob/1657dbb69ca90131359800ef3ef8c919386000cc/demo/example_output/example_out.vcf#L11

Are you sure it is correct?

**Comment by m4merg** [comment]
This example .vcf file produced with the the following reference used for run: brac.fasta, which can be found in 'ref' folder. If you use human genome as reference input, it will produce correct chromosome names and positions in output .vcf file
